# Generated by Django 3.2 on 2021-04-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Time limit in minutes')),
                ('score_to_pass', models.IntegerField(help_text='Required score to pass the quiz')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.category')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
