# Generated by Django 3.2 on 2021-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_to_pass',
            field=models.IntegerField(help_text='Required score to pass the quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(help_text='Time limit in minutes'),
        ),
    ]
