# Generated by Django 3.2 on 2021-04-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20210418_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
    ]
