# Generated by Django 3.2 on 2021-04-20 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeworks.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=2500)),
                ('answer', models.FileField(upload_to='files/', validators=[homeworks.validators.validate_file_size], verbose_name='')),
                ('score', models.PositiveIntegerField()),
                ('score_comment', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
