# Generated by Django 3.2 on 2021-04-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeworks.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='score',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='score_comment',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
        migrations.CreateModel(
            name='AnswerForHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='files/', validators=[homeworks.validators.validate_file_size], verbose_name='')),
                ('score', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=1000)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_answers', to='homeworks.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
