# Generated by Django 3.2 on 2021-04-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeworks.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0002_auto_20210422_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerforhomework',
            name='answer',
            field=models.FileField(upload_to='files/', validators=[homeworks.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='answerforhomework',
            name='score',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='answerforhomework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
